version: '3.8'

services:
  web:
    build: .
    container_name: django_backend_prod
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql_db_prod
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: my_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql_data_prod:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always

volumes:
  mysql_data_prod: